//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WAFC.Reports.org.cgiar.ocs.icraf {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueryEngineV201101Soap", Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class QueryEngineV201101 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTemplatePropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplateResultAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplateResultOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplateResultAsXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSearchCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExpressionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatisticalFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormatInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplateListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplateMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AboutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueryEngineV201101() {
            this.Url = global::WAFC.Reports.Properties.Settings.Default.WAFC_Reports_org_cgiar_ocs_icraf_QueryEngineV201101;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTemplatePropertiesCompletedEventHandler GetTemplatePropertiesCompleted;
        
        /// <remarks/>
        public event GetTemplateResultAsDataSetCompletedEventHandler GetTemplateResultAsDataSetCompleted;
        
        /// <remarks/>
        public event GetTemplateResultOptionsCompletedEventHandler GetTemplateResultOptionsCompleted;
        
        /// <remarks/>
        public event GetTemplateResultAsXMLCompletedEventHandler GetTemplateResultAsXMLCompleted;
        
        /// <remarks/>
        public event GetSearchCriteriaCompletedEventHandler GetSearchCriteriaCompleted;
        
        /// <remarks/>
        public event GetExpressionCompletedEventHandler GetExpressionCompleted;
        
        /// <remarks/>
        public event GetStatisticalFormulaCompletedEventHandler GetStatisticalFormulaCompleted;
        
        /// <remarks/>
        public event GetFormatInfoCompletedEventHandler GetFormatInfoCompleted;
        
        /// <remarks/>
        public event GetTemplateListCompletedEventHandler GetTemplateListCompleted;
        
        /// <remarks/>
        public event GetTemplateMetaDataCompletedEventHandler GetTemplateMetaDataCompleted;
        
        /// <remarks/>
        public event AboutCompletedEventHandler AboutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateProp" +
            "erties", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateProperties GetTemplateProperties(long templateId, WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateProperties", new object[] {
                        templateId,
                        credentials});
            return ((TemplateProperties)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplatePropertiesAsync(long templateId, WSCredentials credentials) {
            this.GetTemplatePropertiesAsync(templateId, credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplatePropertiesAsync(long templateId, WSCredentials credentials, object userState) {
            if ((this.GetTemplatePropertiesOperationCompleted == null)) {
                this.GetTemplatePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplatePropertiesOperationCompleted);
            }
            this.InvokeAsync("GetTemplateProperties", new object[] {
                        templateId,
                        credentials}, this.GetTemplatePropertiesOperationCompleted, userState);
        }
        
        private void OnGetTemplatePropertiesOperationCompleted(object arg) {
            if ((this.GetTemplatePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplatePropertiesCompleted(this, new GetTemplatePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateResu" +
            "ltAsDataSet", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateResultAsDataSet GetTemplateResultAsDataSet(InputForTemplateResult input, WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateResultAsDataSet", new object[] {
                        input,
                        credentials});
            return ((TemplateResultAsDataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplateResultAsDataSetAsync(InputForTemplateResult input, WSCredentials credentials) {
            this.GetTemplateResultAsDataSetAsync(input, credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplateResultAsDataSetAsync(InputForTemplateResult input, WSCredentials credentials, object userState) {
            if ((this.GetTemplateResultAsDataSetOperationCompleted == null)) {
                this.GetTemplateResultAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplateResultAsDataSetOperationCompleted);
            }
            this.InvokeAsync("GetTemplateResultAsDataSet", new object[] {
                        input,
                        credentials}, this.GetTemplateResultAsDataSetOperationCompleted, userState);
        }
        
        private void OnGetTemplateResultAsDataSetOperationCompleted(object arg) {
            if ((this.GetTemplateResultAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplateResultAsDataSetCompleted(this, new GetTemplateResultAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateResu" +
            "ltOptions", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateResultOptions GetTemplateResultOptions(WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateResultOptions", new object[] {
                        credentials});
            return ((TemplateResultOptions)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplateResultOptionsAsync(WSCredentials credentials) {
            this.GetTemplateResultOptionsAsync(credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplateResultOptionsAsync(WSCredentials credentials, object userState) {
            if ((this.GetTemplateResultOptionsOperationCompleted == null)) {
                this.GetTemplateResultOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplateResultOptionsOperationCompleted);
            }
            this.InvokeAsync("GetTemplateResultOptions", new object[] {
                        credentials}, this.GetTemplateResultOptionsOperationCompleted, userState);
        }
        
        private void OnGetTemplateResultOptionsOperationCompleted(object arg) {
            if ((this.GetTemplateResultOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplateResultOptionsCompleted(this, new GetTemplateResultOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateResu" +
            "ltAsXML", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateResultAsXML GetTemplateResultAsXML(InputForTemplateResult input, WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateResultAsXML", new object[] {
                        input,
                        credentials});
            return ((TemplateResultAsXML)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplateResultAsXMLAsync(InputForTemplateResult input, WSCredentials credentials) {
            this.GetTemplateResultAsXMLAsync(input, credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplateResultAsXMLAsync(InputForTemplateResult input, WSCredentials credentials, object userState) {
            if ((this.GetTemplateResultAsXMLOperationCompleted == null)) {
                this.GetTemplateResultAsXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplateResultAsXMLOperationCompleted);
            }
            this.InvokeAsync("GetTemplateResultAsXML", new object[] {
                        input,
                        credentials}, this.GetTemplateResultAsXMLOperationCompleted, userState);
        }
        
        private void OnGetTemplateResultAsXMLOperationCompleted(object arg) {
            if ((this.GetTemplateResultAsXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplateResultAsXMLCompleted(this, new GetTemplateResultAsXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetSearchCriter" +
            "ia", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchCriteria GetSearchCriteria(long templateId, bool hideUnused, WSCredentials credentials) {
            object[] results = this.Invoke("GetSearchCriteria", new object[] {
                        templateId,
                        hideUnused,
                        credentials});
            return ((SearchCriteria)(results[0]));
        }
        
        /// <remarks/>
        public void GetSearchCriteriaAsync(long templateId, bool hideUnused, WSCredentials credentials) {
            this.GetSearchCriteriaAsync(templateId, hideUnused, credentials, null);
        }
        
        /// <remarks/>
        public void GetSearchCriteriaAsync(long templateId, bool hideUnused, WSCredentials credentials, object userState) {
            if ((this.GetSearchCriteriaOperationCompleted == null)) {
                this.GetSearchCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSearchCriteriaOperationCompleted);
            }
            this.InvokeAsync("GetSearchCriteria", new object[] {
                        templateId,
                        hideUnused,
                        credentials}, this.GetSearchCriteriaOperationCompleted, userState);
        }
        
        private void OnGetSearchCriteriaOperationCompleted(object arg) {
            if ((this.GetSearchCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSearchCriteriaCompleted(this, new GetSearchCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetExpression", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Expression GetExpression(long templateId, WSCredentials credentials) {
            object[] results = this.Invoke("GetExpression", new object[] {
                        templateId,
                        credentials});
            return ((Expression)(results[0]));
        }
        
        /// <remarks/>
        public void GetExpressionAsync(long templateId, WSCredentials credentials) {
            this.GetExpressionAsync(templateId, credentials, null);
        }
        
        /// <remarks/>
        public void GetExpressionAsync(long templateId, WSCredentials credentials, object userState) {
            if ((this.GetExpressionOperationCompleted == null)) {
                this.GetExpressionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExpressionOperationCompleted);
            }
            this.InvokeAsync("GetExpression", new object[] {
                        templateId,
                        credentials}, this.GetExpressionOperationCompleted, userState);
        }
        
        private void OnGetExpressionOperationCompleted(object arg) {
            if ((this.GetExpressionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExpressionCompleted(this, new GetExpressionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetStatisticalF" +
            "ormula", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatisticalFormula GetStatisticalFormula(long templateId, WSCredentials credentials) {
            object[] results = this.Invoke("GetStatisticalFormula", new object[] {
                        templateId,
                        credentials});
            return ((StatisticalFormula)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatisticalFormulaAsync(long templateId, WSCredentials credentials) {
            this.GetStatisticalFormulaAsync(templateId, credentials, null);
        }
        
        /// <remarks/>
        public void GetStatisticalFormulaAsync(long templateId, WSCredentials credentials, object userState) {
            if ((this.GetStatisticalFormulaOperationCompleted == null)) {
                this.GetStatisticalFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatisticalFormulaOperationCompleted);
            }
            this.InvokeAsync("GetStatisticalFormula", new object[] {
                        templateId,
                        credentials}, this.GetStatisticalFormulaOperationCompleted, userState);
        }
        
        private void OnGetStatisticalFormulaOperationCompleted(object arg) {
            if ((this.GetStatisticalFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatisticalFormulaCompleted(this, new GetStatisticalFormulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetFormatInfo", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FormatInfo GetFormatInfo(long templateId, WSCredentials credentials) {
            object[] results = this.Invoke("GetFormatInfo", new object[] {
                        templateId,
                        credentials});
            return ((FormatInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormatInfoAsync(long templateId, WSCredentials credentials) {
            this.GetFormatInfoAsync(templateId, credentials, null);
        }
        
        /// <remarks/>
        public void GetFormatInfoAsync(long templateId, WSCredentials credentials, object userState) {
            if ((this.GetFormatInfoOperationCompleted == null)) {
                this.GetFormatInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormatInfoOperationCompleted);
            }
            this.InvokeAsync("GetFormatInfo", new object[] {
                        templateId,
                        credentials}, this.GetFormatInfoOperationCompleted, userState);
        }
        
        private void OnGetFormatInfoOperationCompleted(object arg) {
            if ((this.GetFormatInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormatInfoCompleted(this, new GetFormatInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateList" +
            "", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateList GetTemplateList(string formList, string descrList, WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateList", new object[] {
                        formList,
                        descrList,
                        credentials});
            return ((TemplateList)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplateListAsync(string formList, string descrList, WSCredentials credentials) {
            this.GetTemplateListAsync(formList, descrList, credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplateListAsync(string formList, string descrList, WSCredentials credentials, object userState) {
            if ((this.GetTemplateListOperationCompleted == null)) {
                this.GetTemplateListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplateListOperationCompleted);
            }
            this.InvokeAsync("GetTemplateList", new object[] {
                        formList,
                        descrList,
                        credentials}, this.GetTemplateListOperationCompleted, userState);
        }
        
        private void OnGetTemplateListOperationCompleted(object arg) {
            if ((this.GetTemplateListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplateListCompleted(this, new GetTemplateListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/GetTemplateMeta" +
            "Data", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateMetaData GetTemplateMetaData(long templateId, WSCredentials credentials) {
            object[] results = this.Invoke("GetTemplateMetaData", new object[] {
                        templateId,
                        credentials});
            return ((TemplateMetaData)(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplateMetaDataAsync(long templateId, WSCredentials credentials) {
            this.GetTemplateMetaDataAsync(templateId, credentials, null);
        }
        
        /// <remarks/>
        public void GetTemplateMetaDataAsync(long templateId, WSCredentials credentials, object userState) {
            if ((this.GetTemplateMetaDataOperationCompleted == null)) {
                this.GetTemplateMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplateMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetTemplateMetaData", new object[] {
                        templateId,
                        credentials}, this.GetTemplateMetaDataOperationCompleted, userState);
        }
        
        private void OnGetTemplateMetaDataOperationCompleted(object arg) {
            if ((this.GetTemplateMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplateMetaDataCompleted(this, new GetTemplateMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.agresso.com/QueryEngineService/QueryEngineV201101/About", RequestNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", ResponseNamespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string About() {
            object[] results = this.Invoke("About", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AboutAsync() {
            this.AboutAsync(null);
        }
        
        /// <remarks/>
        public void AboutAsync(object userState) {
            if ((this.AboutOperationCompleted == null)) {
                this.AboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAboutOperationCompleted);
            }
            this.InvokeAsync("About", new object[0], this.AboutOperationCompleted, userState);
        }
        
        private void OnAboutOperationCompleted(object arg) {
            if ((this.AboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AboutCompleted(this, new AboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class WSCredentials {
        
        private string usernameField;
        
        private string clientField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateMetaData {
        
        private SearchCriteria searchCriteriaField;
        
        private TemplateProperties templatePropertiesField;
        
        private FormatInfo formatInfoField;
        
        private Expression expressionField;
        
        private StatisticalFormula statisticalFormulaField;
        
        /// <remarks/>
        public SearchCriteria SearchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public TemplateProperties TemplateProperties {
            get {
                return this.templatePropertiesField;
            }
            set {
                this.templatePropertiesField = value;
            }
        }
        
        /// <remarks/>
        public FormatInfo FormatInfo {
            get {
                return this.formatInfoField;
            }
            set {
                this.formatInfoField = value;
            }
        }
        
        /// <remarks/>
        public Expression Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
        
        /// <remarks/>
        public StatisticalFormula StatisticalFormula {
            get {
                return this.statisticalFormulaField;
            }
            set {
                this.statisticalFormulaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class SearchCriteria {
        
        private int returnCodeField;
        
        private string statusField;
        
        private SearchCriteriaProperties[] searchCriteriaPropertiesListField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public SearchCriteriaProperties[] SearchCriteriaPropertiesList {
            get {
                return this.searchCriteriaPropertiesListField;
            }
            set {
                this.searchCriteriaPropertiesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class SearchCriteriaProperties {
        
        private string columnNameField;
        
        private string descriptionField;
        
        private string restrictionTypeField;
        
        private string fromValueField;
        
        private string toValueField;
        
        private int dataTypeField;
        
        private int dataLengthField;
        
        private int dataCaseField;
        
        private bool isParameterField;
        
        private bool isVisibleField;
        
        private bool isPromptField;
        
        private bool isMandatoryField;
        
        private bool canBeOverriddenField;
        
        private string relDateCritField;
        
        /// <remarks/>
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RestrictionType {
            get {
                return this.restrictionTypeField;
            }
            set {
                this.restrictionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FromValue {
            get {
                return this.fromValueField;
            }
            set {
                this.fromValueField = value;
            }
        }
        
        /// <remarks/>
        public string ToValue {
            get {
                return this.toValueField;
            }
            set {
                this.toValueField = value;
            }
        }
        
        /// <remarks/>
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public int DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
            }
        }
        
        /// <remarks/>
        public int DataCase {
            get {
                return this.dataCaseField;
            }
            set {
                this.dataCaseField = value;
            }
        }
        
        /// <remarks/>
        public bool IsParameter {
            get {
                return this.isParameterField;
            }
            set {
                this.isParameterField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrompt {
            get {
                return this.isPromptField;
            }
            set {
                this.isPromptField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMandatory {
            get {
                return this.isMandatoryField;
            }
            set {
                this.isMandatoryField = value;
            }
        }
        
        /// <remarks/>
        public bool CanBeOverridden {
            get {
                return this.canBeOverriddenField;
            }
            set {
                this.canBeOverriddenField = value;
            }
        }
        
        /// <remarks/>
        public string RelDateCrit {
            get {
                return this.relDateCritField;
            }
            set {
                this.relDateCritField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateProperties {
        
        private string aggregateIdField;
        
        private string extraTablesField;
        
        private string extraWhereField;
        
        private string frameField;
        
        private string nameField;
        
        private string table1Field;
        
        private string table2Field;
        
        private string table3Field;
        
        private string versionField;
        
        private string versionMinorField;
        
        private bool aggregatedField;
        
        private bool autoFindField;
        
        private bool isBrowseTableField;
        
        private bool useTable1Field;
        
        private bool useTable2Field;
        
        private bool useTable3Field;
        
        private int dWPeriodField;
        
        private int startLevelField;
        
        private long maxRowsField;
        
        private long templateIdField;
        
        /// <remarks/>
        public string AggregateId {
            get {
                return this.aggregateIdField;
            }
            set {
                this.aggregateIdField = value;
            }
        }
        
        /// <remarks/>
        public string ExtraTables {
            get {
                return this.extraTablesField;
            }
            set {
                this.extraTablesField = value;
            }
        }
        
        /// <remarks/>
        public string ExtraWhere {
            get {
                return this.extraWhereField;
            }
            set {
                this.extraWhereField = value;
            }
        }
        
        /// <remarks/>
        public string Frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Table1 {
            get {
                return this.table1Field;
            }
            set {
                this.table1Field = value;
            }
        }
        
        /// <remarks/>
        public string Table2 {
            get {
                return this.table2Field;
            }
            set {
                this.table2Field = value;
            }
        }
        
        /// <remarks/>
        public string Table3 {
            get {
                return this.table3Field;
            }
            set {
                this.table3Field = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string VersionMinor {
            get {
                return this.versionMinorField;
            }
            set {
                this.versionMinorField = value;
            }
        }
        
        /// <remarks/>
        public bool Aggregated {
            get {
                return this.aggregatedField;
            }
            set {
                this.aggregatedField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoFind {
            get {
                return this.autoFindField;
            }
            set {
                this.autoFindField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBrowseTable {
            get {
                return this.isBrowseTableField;
            }
            set {
                this.isBrowseTableField = value;
            }
        }
        
        /// <remarks/>
        public bool UseTable1 {
            get {
                return this.useTable1Field;
            }
            set {
                this.useTable1Field = value;
            }
        }
        
        /// <remarks/>
        public bool UseTable2 {
            get {
                return this.useTable2Field;
            }
            set {
                this.useTable2Field = value;
            }
        }
        
        /// <remarks/>
        public bool UseTable3 {
            get {
                return this.useTable3Field;
            }
            set {
                this.useTable3Field = value;
            }
        }
        
        /// <remarks/>
        public int DWPeriod {
            get {
                return this.dWPeriodField;
            }
            set {
                this.dWPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int StartLevel {
            get {
                return this.startLevelField;
            }
            set {
                this.startLevelField = value;
            }
        }
        
        /// <remarks/>
        public long MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
            }
        }
        
        /// <remarks/>
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class FormatInfo {
        
        private FormatProperties[] formatPropertiesListField;
        
        /// <remarks/>
        public FormatProperties[] FormatPropertiesList {
            get {
                return this.formatPropertiesListField;
            }
            set {
                this.formatPropertiesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class FormatProperties {
        
        private string amountDisplayFormatField;
        
        private string attributeIdField;
        
        private string breakColNameField;
        
        private string breakTextField;
        
        private string colorField;
        
        private string columnHeaderTextField;
        
        private string columnNameField;
        
        private string conditionTypeField;
        
        private string fontFamilyField;
        
        private string formulaField;
        
        private string sectionTypeField;
        
        private string sectionFormatIDField;
        
        private string typeField;
        
        private bool breakField;
        
        private bool conditionInUseField;
        
        private bool conditionOnlyBreaksField;
        
        private bool fontBoldField;
        
        private bool fontItalicField;
        
        private bool fontStrikeOutField;
        
        private bool fontUnderlineField;
        
        private bool showField;
        
        private bool showTextField;
        
        private int conditionLevelField;
        
        private int dataCaseField;
        
        private int dataLengthField;
        
        private int dataTypeField;
        
        private int displayLengthField;
        
        private int displayOrderField;
        
        private int sortOrderField;
        
        private int textDisplayLengthField;
        
        private int sequenceNoField;
        
        private double conditionFromField;
        
        private double conditionToField;
        
        /// <remarks/>
        public string AmountDisplayFormat {
            get {
                return this.amountDisplayFormatField;
            }
            set {
                this.amountDisplayFormatField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
        
        /// <remarks/>
        public string BreakColName {
            get {
                return this.breakColNameField;
            }
            set {
                this.breakColNameField = value;
            }
        }
        
        /// <remarks/>
        public string BreakText {
            get {
                return this.breakTextField;
            }
            set {
                this.breakTextField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string ColumnHeaderText {
            get {
                return this.columnHeaderTextField;
            }
            set {
                this.columnHeaderTextField = value;
            }
        }
        
        /// <remarks/>
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FontFamily {
            get {
                return this.fontFamilyField;
            }
            set {
                this.fontFamilyField = value;
            }
        }
        
        /// <remarks/>
        public string Formula {
            get {
                return this.formulaField;
            }
            set {
                this.formulaField = value;
            }
        }
        
        /// <remarks/>
        public string SectionType {
            get {
                return this.sectionTypeField;
            }
            set {
                this.sectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SectionFormatID {
            get {
                return this.sectionFormatIDField;
            }
            set {
                this.sectionFormatIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool Break {
            get {
                return this.breakField;
            }
            set {
                this.breakField = value;
            }
        }
        
        /// <remarks/>
        public bool ConditionInUse {
            get {
                return this.conditionInUseField;
            }
            set {
                this.conditionInUseField = value;
            }
        }
        
        /// <remarks/>
        public bool ConditionOnlyBreaks {
            get {
                return this.conditionOnlyBreaksField;
            }
            set {
                this.conditionOnlyBreaksField = value;
            }
        }
        
        /// <remarks/>
        public bool FontBold {
            get {
                return this.fontBoldField;
            }
            set {
                this.fontBoldField = value;
            }
        }
        
        /// <remarks/>
        public bool FontItalic {
            get {
                return this.fontItalicField;
            }
            set {
                this.fontItalicField = value;
            }
        }
        
        /// <remarks/>
        public bool FontStrikeOut {
            get {
                return this.fontStrikeOutField;
            }
            set {
                this.fontStrikeOutField = value;
            }
        }
        
        /// <remarks/>
        public bool FontUnderline {
            get {
                return this.fontUnderlineField;
            }
            set {
                this.fontUnderlineField = value;
            }
        }
        
        /// <remarks/>
        public bool Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowText {
            get {
                return this.showTextField;
            }
            set {
                this.showTextField = value;
            }
        }
        
        /// <remarks/>
        public int ConditionLevel {
            get {
                return this.conditionLevelField;
            }
            set {
                this.conditionLevelField = value;
            }
        }
        
        /// <remarks/>
        public int DataCase {
            get {
                return this.dataCaseField;
            }
            set {
                this.dataCaseField = value;
            }
        }
        
        /// <remarks/>
        public int DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
            }
        }
        
        /// <remarks/>
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayLength {
            get {
                return this.displayLengthField;
            }
            set {
                this.displayLengthField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public int TextDisplayLength {
            get {
                return this.textDisplayLengthField;
            }
            set {
                this.textDisplayLengthField = value;
            }
        }
        
        /// <remarks/>
        public int SequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
            }
        }
        
        /// <remarks/>
        public double ConditionFrom {
            get {
                return this.conditionFromField;
            }
            set {
                this.conditionFromField = value;
            }
        }
        
        /// <remarks/>
        public double ConditionTo {
            get {
                return this.conditionToField;
            }
            set {
                this.conditionToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class Expression {
        
        private int returnCodeField;
        
        private string statusField;
        
        private ExpressionProperties[] expressionPropertiesListField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ExpressionProperties[] ExpressionPropertiesList {
            get {
                return this.expressionPropertiesListField;
            }
            set {
                this.expressionPropertiesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class ExpressionProperties {
        
        private string formulaField;
        
        private string colNameField;
        
        private bool isRunningTotalField;
        
        private bool hasSumField;
        
        private bool hasVerticalSumField;
        
        /// <remarks/>
        public string Formula {
            get {
                return this.formulaField;
            }
            set {
                this.formulaField = value;
            }
        }
        
        /// <remarks/>
        public string ColName {
            get {
                return this.colNameField;
            }
            set {
                this.colNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRunningTotal {
            get {
                return this.isRunningTotalField;
            }
            set {
                this.isRunningTotalField = value;
            }
        }
        
        /// <remarks/>
        public bool HasSum {
            get {
                return this.hasSumField;
            }
            set {
                this.hasSumField = value;
            }
        }
        
        /// <remarks/>
        public bool HasVerticalSum {
            get {
                return this.hasVerticalSumField;
            }
            set {
                this.hasVerticalSumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class StatisticalFormula {
        
        private int returnCodeField;
        
        private string statusField;
        
        private StatisticalFormulaProperties[] statisticalFormulaPropertiesListField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public StatisticalFormulaProperties[] StatisticalFormulaPropertiesList {
            get {
                return this.statisticalFormulaPropertiesListField;
            }
            set {
                this.statisticalFormulaPropertiesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class StatisticalFormulaProperties {
        
        private string formulaField;
        
        private string colNameField;
        
        private bool excludeZeroField;
        
        private string displayMethodField;
        
        private string displayColumnField;
        
        /// <remarks/>
        public string Formula {
            get {
                return this.formulaField;
            }
            set {
                this.formulaField = value;
            }
        }
        
        /// <remarks/>
        public string ColName {
            get {
                return this.colNameField;
            }
            set {
                this.colNameField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcludeZero {
            get {
                return this.excludeZeroField;
            }
            set {
                this.excludeZeroField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayMethod {
            get {
                return this.displayMethodField;
            }
            set {
                this.displayMethodField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayColumn {
            get {
                return this.displayColumnField;
            }
            set {
                this.displayColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateHeader {
        
        private long templateIdField;
        
        private string companyCodeField;
        
        private string frameField;
        
        private string functionIdField;
        
        private string moduleField;
        
        private string nameField;
        
        private string userIdField;
        
        /// <remarks/>
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
            }
        }
        
        /// <remarks/>
        public string FunctionId {
            get {
                return this.functionIdField;
            }
            set {
                this.functionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateList {
        
        private TemplateHeader[] templateHeaderListField;
        
        /// <remarks/>
        public TemplateHeader[] TemplateHeaderList {
            get {
                return this.templateHeaderListField;
            }
            set {
                this.templateHeaderListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateResultAsXML {
        
        private int returnCodeField;
        
        private string statusField;
        
        private string templateResultField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TemplateResult {
            get {
                return this.templateResultField;
            }
            set {
                this.templateResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateResultAsDataSet {
        
        private int returnCodeField;
        
        private string statusField;
        
        private System.Data.DataSet templateResultField;
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet TemplateResult {
            get {
                return this.templateResultField;
            }
            set {
                this.templateResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class TemplateResultOptions {
        
        private bool showDescriptionsField;
        
        private bool aggregatedField;
        
        private bool overrideAggregationField;
        
        private bool calculateFormulasField;
        
        private bool formatAlternativeBreakColumnsField;
        
        private bool removeHiddenColumnsField;
        
        private string filterField;
        
        private long firstRecordField;
        
        private long lastRecordField;
        
        /// <remarks/>
        public bool ShowDescriptions {
            get {
                return this.showDescriptionsField;
            }
            set {
                this.showDescriptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool Aggregated {
            get {
                return this.aggregatedField;
            }
            set {
                this.aggregatedField = value;
            }
        }
        
        /// <remarks/>
        public bool OverrideAggregation {
            get {
                return this.overrideAggregationField;
            }
            set {
                this.overrideAggregationField = value;
            }
        }
        
        /// <remarks/>
        public bool CalculateFormulas {
            get {
                return this.calculateFormulasField;
            }
            set {
                this.calculateFormulasField = value;
            }
        }
        
        /// <remarks/>
        public bool FormatAlternativeBreakColumns {
            get {
                return this.formatAlternativeBreakColumnsField;
            }
            set {
                this.formatAlternativeBreakColumnsField = value;
            }
        }
        
        /// <remarks/>
        public bool RemoveHiddenColumns {
            get {
                return this.removeHiddenColumnsField;
            }
            set {
                this.removeHiddenColumnsField = value;
            }
        }
        
        /// <remarks/>
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public long FirstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
            }
        }
        
        /// <remarks/>
        public long LastRecord {
            get {
                return this.lastRecordField;
            }
            set {
                this.lastRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV201101")]
    public partial class InputForTemplateResult {
        
        private long templateIdField;
        
        private TemplateResultOptions templateResultOptionsField;
        
        private SearchCriteriaProperties[] searchCriteriaPropertiesListField;
        
        private string pipelineAssociatedNameField;
        
        /// <remarks/>
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        public TemplateResultOptions TemplateResultOptions {
            get {
                return this.templateResultOptionsField;
            }
            set {
                this.templateResultOptionsField = value;
            }
        }
        
        /// <remarks/>
        public SearchCriteriaProperties[] SearchCriteriaPropertiesList {
            get {
                return this.searchCriteriaPropertiesListField;
            }
            set {
                this.searchCriteriaPropertiesListField = value;
            }
        }
        
        /// <remarks/>
        public string PipelineAssociatedName {
            get {
                return this.pipelineAssociatedNameField;
            }
            set {
                this.pipelineAssociatedNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplatePropertiesCompletedEventHandler(object sender, GetTemplatePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplatePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplatePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateProperties Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateProperties)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplateResultAsDataSetCompletedEventHandler(object sender, GetTemplateResultAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplateResultAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplateResultAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateResultAsDataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateResultAsDataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplateResultOptionsCompletedEventHandler(object sender, GetTemplateResultOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplateResultOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplateResultOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateResultOptions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateResultOptions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplateResultAsXMLCompletedEventHandler(object sender, GetTemplateResultAsXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplateResultAsXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplateResultAsXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateResultAsXML Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateResultAsXML)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetSearchCriteriaCompletedEventHandler(object sender, GetSearchCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSearchCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSearchCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchCriteria Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchCriteria)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetExpressionCompletedEventHandler(object sender, GetExpressionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExpressionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExpressionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Expression Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Expression)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetStatisticalFormulaCompletedEventHandler(object sender, GetStatisticalFormulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatisticalFormulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatisticalFormulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatisticalFormula Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatisticalFormula)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetFormatInfoCompletedEventHandler(object sender, GetFormatInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormatInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormatInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FormatInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FormatInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplateListCompletedEventHandler(object sender, GetTemplateListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplateListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplateListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetTemplateMetaDataCompletedEventHandler(object sender, GetTemplateMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplateMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplateMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateMetaData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateMetaData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AboutCompletedEventHandler(object sender, AboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591